export const keywords = [
    // Web Design Keywords
    'web-design-toronto',
    'web-design-markham',
    'web-design-richmond-hill',
    'web-design-vaughan',
    'web-design-etobicoke',
    'web-design-oshawa',
    'web-design-scarborough',
    'web-design-hamilton',
    'web-design-london',
    'web-design-waterloo',
    'web-design-cambridge',
    'web-design-mississauga',

    // SEO Keywords
    'seo-services-toronto',
    'seo-services-markham',
    'seo-services-richmond-hill',
    'seo-services-vaughan',
    'seo-services-etobicoke',
    'seo-services-oshawa',
    'seo-services-scarborough',
    'seo-services-hamilton',
    'seo-services-london',
    'seo-services-waterloo',
    'seo-services-cambridge',
    'seo-services-mississauga',

    // Digital Marketing Keywords 
    'digital-marketing-toronto',
    'digital-marketing-markham',
    'digital-marketing-richmond-hill',
    'digital-marketing-vaughan',
    'digital-marketing-etobicoke',
    'digital-marketing-oshawa',
    'digital-marketing-scarborough',
    'digital-marketing-hamilton',
    'digital-marketing-london',
    'digital-marketing-waterloo',
    'digital-marketing-cambridge',
    'digital-marketing-mississauga',

    'website-redesign-toronto',
    'website-redesign-markham',
    'website-redesign-richmond-hill',
    'website-redesign-vaughan',
    'website-redesign-etobicoke',
    'website-redesign-oshawa',
    'website-redesign-scarborough',
    'website-redesign-hamilton',
    'website-redesign-london',
    'website-redesign-waterloo',
    'website-redesign-cambridge',
    'website-redesign-mississauga',

    'website-development-toronto',
    'website-development-markham',
    'website-development-richmond-hill',
    'website-development-vaughan',
    'website-development-etobicoke',
    'website-development-oshawa',
    'website-development-scarborough',
    'website-development-hamilton',
    'website-development-london',
    'website-development-waterloo',
    'website-development-cambridge',
    'website-development-mississauga',

    'ecommerce-website-development-toronto',
    'ecommerce-website-development-markham',
    'ecommerce-website-development-richmond-hill',
    'ecommerce-website-development-vaughan',
    'ecommerce-website-development-etobicoke',
    'ecommerce-website-development-oshawa',
    'ecommerce-website-development-scarborough',
    'ecommerce-website-development-hamilton',
    'ecommerce-website-development-london',
    'ecommerce-website-development-waterloo',
    'ecommerce-website-development-cambridge',
    'ecommerce-website-development-mississauga',

    'ecommerce-website-design-toronto',
    'ecommerce-website-design-markham',
    'ecommerce-website-design-richmond-hill',
    'ecommerce-website-design-vaughan',
    'ecommerce-website-design-etobicoke',
    'ecommerce-website-design-oshawa',
    'ecommerce-website-design-scarborough',
    'ecommerce-website-design-hamilton',
    'ecommerce-website-design-london',
    'ecommerce-website-design-waterloo',
    'ecommerce-website-design-cambridge',
    'ecommerce-website-design-mississauga',

    'ecommerce-seo-toronto',
    'ecommerce-seo-markham',
    'ecommerce-seo-richmond-hill',
    'ecommerce-seo-vaughan',
    'ecommerce-seo-etobicoke',
    'ecommerce-seo-oshawa',
    'ecommerce-seo-scarborough',
    'ecommerce-seo-hamilton',
    'ecommerce-seo-london',
    'ecommerce-seo-waterloo',
    'ecommerce-seo-cambridge',
    'ecommerce-seo-mississauga',

    // Digital Advertising Keywords 
    'digital-advertising-toronto',
    'digital-advertising-markham',
    'digital-advertising-richmond-hill',
    'digital-advertising-vaughan',
    'digital-advertising-etobicoke',
    'digital-advertising-oshawa',
    'digital-advertising-scarborough',
    'digital-advertising-hamilton',
    'digital-advertising-london',
    'digital-advertising-waterloo',
    'digital-advertising-cambridge',
    'digital-advertising-mississauga',
];
