export const keywords = [
    // Web Design Keywords
    'web-design-toronto',
    'web-design-markham',
    'web-design-richmond-hill',
    'web-design-Kitchener',
    'web-design-etobicoke',
    'web-design-oshawa',
    'web-design-scarborough',
    'web-design-hamilton',
    'web-design-london',
    'web-design-waterloo',
    'web-design-cambridge',
    'web-design-mississauga',

    'website-development-toronto',
    'website-development-markham',
    'website-development-richmond-hill',
    'website-development-Kitchener',
    'website-development-etobicoke',
    'website-development-oshawa',
    'website-development-scarborough',
    'website-development-hamilton',
    'website-development-london',
    'website-development-waterloo',
    'website-development-cambridge',
    'website-development-mississauga',

    'ecommerce-website-development-toronto',
    'ecommerce-website-development-markham',
    'ecommerce-website-development-richmond-hill',
    'ecommerce-website-development-Kitchener',
    'ecommerce-website-development-etobicoke',
    'ecommerce-website-development-oshawa',
    'ecommerce-website-development-scarborough',
    'ecommerce-website-development-hamilton',
    'ecommerce-website-development-london',
    'ecommerce-website-development-waterloo',
    'ecommerce-website-development-cambridge',
    'ecommerce-website-development-mississauga',

    'ecommerce-website-design-toronto',
    'ecommerce-website-design-markham',
    'ecommerce-website-design-richmond-hill',
    'ecommerce-website-design-Kitchener',
    'ecommerce-website-design-etobicoke',
    'ecommerce-website-design-oshawa',
    'ecommerce-website-design-scarborough',
    'ecommerce-website-design-hamilton',
    'ecommerce-website-design-london',
    'ecommerce-website-design-waterloo',
    'ecommerce-website-design-cambridge',
    'ecommerce-website-design-mississauga',

];
